# Generated by Django 5.0.3 on 2024-04-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('F', 'Filme'), ('S', 'Série')], default='F', max_length=1)),
                ('genero1', models.CharField(choices=[('Ac', 'Ação'), ('Av', 'Aventura'), ('C', 'Comédia'), ('D', 'Drama'), ('Fan', 'Fantasia'), ('Fic', 'Ficção cientifica'), ('M', 'Mistério'), ('R', 'Romance'), ('T', 'Terror')], default='Ac', max_length=3)),
                ('genero2', models.CharField(choices=[('Ac', 'Ação'), ('Av', 'Aventura'), ('C', 'Comédia'), ('D', 'Drama'), ('Fan', 'Fantasia'), ('Fic', 'Ficção cientifica'), ('M', 'Mistério'), ('R', 'Romance'), ('T', 'Terror')], default='Av', max_length=3)),
                ('imagem', models.CharField(max_length=11)),
            ],
        ),
    ]
