# Generated by Django 5.0.3 on 2024-04-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
