# Generated by Django 5.0.3 on 2024-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_alter_filme_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
