# Generated by Django 5.0.3 on 2024-04-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_filme_assistido'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='genero3',
            field=models.CharField(choices=[('Ac', 'Ação'), ('Av', 'Aventura'), ('C', 'Comédia'), ('D', 'Drama'), ('Fan', 'Fantasia'), ('Fic', 'Ficção cientifica'), ('M', 'Mistério'), ('R', 'Romance'), ('T', 'Terror')], default='C', max_length=3),
        ),
    ]
