# Generated by Django 5.0.3 on 2024-04-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_filme_genero3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
