# Generated by Django 5.0.3 on 2024-05-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0006_alter_filme_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='imagem',
        ),
    ]
